### ISSUE TITLE
Assertion errors

### ISSUE THREAD

**Issue by Zethson** [fmfn/BayesianOptimization#112]
Hi,

I'm currently trying to evaluate an xgboost tree.

The error that I receive:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mhc_1-0.1.dev0-py3.7.egg/EGG-INFO/scripts/mhc-1", line 61, in parse_CLI_start_tool
    classifier = gbtrees_train(encoded_aminoacids, binding_values, silent)
  File "/usr/lib/python3.7/site-packages/mhc_1-0.1.dev0-py3.7.egg/src/algorithms/ml/gbtrees/gbtrees_training.py", line 56, in gbtrees_train
    perform_bayesian_optimization(peptides_train, peptides_test)
  File "/usr/lib/python3.7/site-packages/mhc_1-0.1.dev0-py3.7.egg/src/algorithms/ml/gbtrees/bayesian_optimization_search.py", line 63, in perform_bayesian_optimization
    }, train, labels)
  File "/usr/lib/python3.7/site-packages/bayesian_optimization-0.6.0-py3.7.egg/bayes_opt/bayesian_optimization.py", line 30, in __init__
    self.random_state = ensure_rng(random_state)
  File "/usr/lib/python3.7/site-packages/bayesian_optimization-0.6.0-py3.7.egg/bayes_opt/helpers.py", line 154, in ensure_rng
    assert isinstance(random_state, np.random.RandomState)
AssertionError

https://paste.ofcode.org/cB9CQWjL4ejcfCJsHPvM8V

My implementation for the evaluation. Do you have any idea about why the assertion error occurs in your helper function?

**Comment by Zethson** [comment]
Nevermind, I was blind.

**Comment by lxgend** [comment]
> Nevermind, I was blind.

Same problem. How did you solve it?

**Comment by Zethson** [comment]
@lxgend I honestly do not remember, but it must have been super trivial, because else I would have posted the answer here (if just for me).

**Comment by lxgend** [comment]
> @lxgend I honestly do not remember, but it must have been super trivial, because else I would have posted the answer here (if just for me).

You are right. I solved it, too.

**Comment by Zethson** [comment]
So what was the mistake that you/we did? :)
