### ISSUE TITLE
Error while running async_optmization.py

### ISSUE THREAD

**Issue by jjiteshh** [fmfn/BayesianOptimization#135]
Hi,

I was trying to learn how to use the Optmizer in a distributed way. I tried to run the async_optmization.py in the examples folder.

I am getting the below error. 

optimizer 3 wants to register: {}.
optimizer 3 got -7.35793220819907 as target.
optimizer 3 will to register next: {'params': {'x': 2.535584435045286, 'y': 2.3887922022229056}, 'target': -7.35793220819907}.

ERROR:tornado.application:Uncaught exception POST /bayesian_optimization (::1)
HTTPServerRequest(protocol='http', host='localhost:9009', method='POST', uri='/bayesian_optimization', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:9009', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '90', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/Jitesh/Desktop/Kite/async.py", line 48, in post
    target=body["target"],
TypeError: register() got an unexpected keyword argument 'x'
ERROR:tornado.access:500 POST /bayesian_optimization (::1) 79.53ms
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Jitesh/Desktop/Kite/async.py", line 84, in run_optimizer
    json=register_data,
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

optimizer 1 wants to register: {}.
optimizer 1 got -18.518887397481908 as target.
optimizer 1 will to register next: {'params': {'x': -2.2980808727542117, 'y': -2.7732892414660117}, 'target': -18.518887397481908}.

optimizer 2 wants to register: {}.
optimizer 2 got -16.925509488264787 as target.
optimizer 2 will to register next: {'params': {'x': 1.5604247824973552, 'y': -2.9358079204189917}, 'target': -16.925509488264787}.

ERROR:tornado.application:Uncaught exception POST /bayesian_optimization (::1)
HTTPServerRequest(protocol='http', host='localhost:9009', method='POST', uri='/bayesian_optimization', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:9009', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '95', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/Jitesh/Desktop/Kite/async.py", line 48, in post
    target=body["target"],
TypeError: register() got an unexpected keyword argument 'x'
ERROR:tornado.access:500 POST /bayesian_optimization (::1) 0.66ms
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Jitesh/Desktop/Kite/async.py", line 84, in run_optimizer
    json=register_data,
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR:tornado.application:Uncaught exception POST /bayesian_optimization (::1)
HTTPServerRequest(protocol='http', host='localhost:9009', method='POST', uri='/bayesian_optimization', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:9009', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '94', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
 File "/Users/Jitesh/Desktop/Kite/async.py", line 48, in post
    target=body["target"],
TypeError: register() got an unexpected keyword argument 'x'
ERROR:tornado.access:500 POST /bayesian_optimization (::1) 0.98ms
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/Jitesh/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Jitesh/Desktop/Kite/async.py", line 84, in run_optimizer
    json=register_data,
  File "/Users/Jitesh/anaconda3/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Jitesh/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[Finished in 18.785s]
Git
GitHub
async.py00051:25Autopep8: √
LFUTF-8Python0 files4 updates

**Comment by fmfn** [comment]
Oh, I see what the error is, I'll push a fix soon. In the mean time, try changing line 48 from `x=body["params"]` to `params=body["params"]` and see if that fixes it.

**Comment by fmfn** [comment]
This should be fixed in the master branch once #136 is merged. It will be available on pip once a new release is out (no planned date yet).
