### ISSUE TITLE
inf/NaN bug

### ISSUE THREAD

**Issue by BaldwinTheThird** [fmfn/BayesianOptimization#20]
I am getting a strange error when running a slightly modified example you provided (added factor y):

from bayes_opt import BayesianOptimization
import numpy as np

```
def target(x,y):
    return (np.exp(-(x - 2)**2) + np.exp(-(x - 6)**2/10) + 1/ (x**2 + 1))*y

bo = BayesianOptimization(target, {'x': (-2,10),'y':(1,2)})

gp_params = {'corr': 'cubic'}
bo.maximize(init_points=2, n_iter=15, acq='ucb', kappa=5, **gp_params)
```
here is the complete trace back:

```
Optimization failed. Try increasing the ``nugget``
capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 807, in runfile
    execfile(filename, namespace)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 95, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/SciSoft/WinPython-64bit-3.5.1.1/python-3.5.1.amd64/Scripts/bay_opt_test.py", line 10, in <module>
    bo.maximize(init_points=2, n_iter=15, acq='ucb', kappa=5, **gp_params)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\Lib\site-packages\BayesianOptimization\bayes_opt\bayesian_optimization.py", line 326, in maximize
    self.gp.fit(self.X[ur], self.Y[ur])
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\sklearn\gaussian_process\gaussian_process.py", line 340, in fit
    self._arg_max_reduced_likelihood_function()
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\sklearn\gaussian_process\gaussian_process.py", line 734, in _arg_max_reduced_likelihood_function
    raise ve
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\sklearn\gaussian_process\gaussian_process.py", line 731, in _arg_max_reduced_likelihood_function
    iprint=0)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\cobyla.py", line 172, in fmin_cobyla
    **opts)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\cobyla.py", line 258, in _minimize_cobyla
    dinfo=info)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\optimize\cobyla.py", line 248, in calcfc
    f = fun(x, *args)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\sklearn\gaussian_process\gaussian_process.py", line 704, in minus_reduced_likelihood_function
    theta=10. ** log10t)[0]
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\sklearn\gaussian_process\gaussian_process.py", line 606, in reduced_likelihood_function
    C = linalg.cholesky(R, lower=True)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\linalg\decomp_cholesky.py", line 81, in cholesky
    check_finite=check_finite)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\scipy\linalg\decomp_cholesky.py", line 20, in _cholesky
    a1 = asarray_chkfinite(a)
  File "C:\SciSoft\WinPython-64bit-3.5.1.1\python-3.5.1.amd64\lib\site-packages\numpy\lib\function_base.py", line 1022, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```
I don't see what is wrong with the function.  When I set 'nugget' to 1e-1 the error no longer occurs. What exactly does nugget do?

**Comment by fmfn** [comment]
Yeah, cubic correlation is tricky, and often leads to this kind of problem, you change it to absolute_exponential, for example, it works fine.

The nugget is essentially a term added to the diagonal of the correlation matrix that helps stabilizing the matrix inversion step and, in the case of gaussian kernel, can be interpreted as having noisy labels (uncertainty  in the y values).

**Comment by BaldwinTheThird** [comment]
that makes a lot of sense. thanks
