### ISSUE TITLE
AssertionError during discrete parameters

### ISSUE THREAD

**Issue by lalimili6** [fmfn/BayesianOptimization#269]
@fmfn 
Hi, dear
Thanks for this library.
I want to do bayesian optimizer for discrete parameters, simply code like below, I follow advance tour:
```
import os
import sys
from bayes_opt import BayesianOptimization
def func_with_discrete_params(dim, bottleneck_dim):
    print(dim,bottleneck_dim)
    assert dim % 32 == 0
    assert bottleneck_dim  % 32 == 0
    result = dim+bottleneck_dim
    return result

def function_to_be_optimized(dim, bottleneck_dim):
    dim = int(dim)
    bottleneck_dim =int(bottleneck_dim)
    return func_with_discrete_params(dim,bottleneck_dim)


optimizer = BayesianOptimization(
    f=function_to_be_optimized,
    pbounds={'dim': (1024,1536 ), 'bottleneck_dim': (128,256)},
    verbose=2,
    random_state=1,
)

optimizer.maximize(
    init_points=2,
    n_iter=4,
)
```

but I get the error below, how can fix it?
```
|   iter    |  target   | bottle... |    dim    |
-------------------------------------------------
1392 181
Traceback (most recent call last):
  File "/home/sokhan/.local/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (181.3788166019295, 1392.806140642385)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/sokhan/.local/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 185, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/sokhan/.local/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 116, in probe
    self._space.probe(params)
  File "/home/sokhan/.local/lib/python3.6/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "<stdin>", line 4, in function_to_be_optimized
  File "<stdin>", line 4, in func_with_discrete_params
AssertionError
```

best regards

**Comment by bwheelz36** [comment]
```assert dim % 32 == 0```
this line states that the residual of dim/32 should be 0. it isn't, hence the error.

**Comment by mazhilong133** [comment]
in probe
    target = self.target_func(**dict_params)？

**Comment by mazhilong133** [comment]
target = self.target_func(**dict_params)

        if self._constraint is None:
            self.register(x, target)
            return target

        constraint_value = self._constraint.eval(**dict_params)
        self.register(x, target, constraint_value)
        return target, constraint_value



line 431, in probe
    target = self.target_func(**dict_params)，Why?
