### ISSUE TITLE
ValueError: continuous is not supported

### ISSUE THREAD

**Issue by Waffleboy** [fmfn/BayesianOptimization#65]
Hey, Just found out about this library and it looks really cool!

I was trying it out on a sample dataset with the example script given (https://github.com/fmfn/BayesianOptimization/blob/master/examples/sklearn_example.py) and i kept encountering this error.

Could anyone point me as to how to resolve it? It seems strange that you cant use Bayesian Optimization for continuous variables as theoretically shouldn't you be able to?

**Comment by fmfn** [comment]
Can you provide the entire error message and some more context?

**Comment by Waffleboy** [comment]
Sure,

```
Initialization
-----------------------------------------------------------------
 Step |   Time |      Value |   max_depth |   min_samples_split | 
Traceback (most recent call last):

  File "<ipython-input-21-7d72ab55a068>", line 9, in <module>
    rfcBO.maximize(n_iter=10, **gp_params)

  File "/storage/anaconda3/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 249, in maximize
    self.init(init_points)

  File "/storage/anaconda3/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 104, in init
    y_init.append(self.f(**dict(zip(self.keys, x))))

  File "<ipython-input-20-bad8a5dc3d31>", line 4, in rfccv
    train_dataset_x, train_dataset_y, 'f1', cv=3

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py", line 1581, in cross_val_score
    for train, test in cv)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py", line 1694, in _fit_and_score
    test_score = _score(estimator, X_test, y_test, scorer)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py", line 1751, in _score
    score = scorer(estimator, X_test, y_test)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/metrics/scorer.py", line 108, in __call__
    **self._kwargs)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 714, in f1_score
    sample_weight=sample_weight)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 828, in fbeta_score
    sample_weight=sample_weight)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1025, in precision_recall_fscore_support
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)

  File "/storage/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 88, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))

ValueError: continuous is not supported
```

I venture it's due to my target variable being continuous in nature?

**Comment by fmfn** [comment]
This is not a BayesianOptimization problem. You're passing a continuous label to a scikit-learn metric that does not support it.
