### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by philip-fu** [fmfn/BayesianOptimization#70]
When i run:
pip install bayesian-optimization

i got:
TypeError: string argument expected, got 'NoneType'

Here the whole thing:
Requirement already satisfied: bayesian-optimization in c:\programdata\anaconda3\lib\site-packages\bayesian_optimization-0.4.0-py3.6.egg
Requirement already satisfied: numpy>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from bayesian-optimization)
Requirement already satisfied: scipy>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from bayesian-optimization)
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\ProgramData\Anaconda3\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "C:\ProgramData\Anaconda3\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

**Comment by philip-fu** [comment]
btw i am using win10, anaconda3, python 3.6

**Comment by fmfn** [comment]
This package was not explicitly uploaded to anaconda, and to be honest I'm not too familiar with how nicely `pip` and `conda`  play together. Nevertheless I will close this issue since its stale.
